"""30 fixed prompts for the parity and perplexity harnesses (PLAN.md 4.7). Do not reorder."""
PROMPTS = [
    "Explain why the sky is blue in two short paragraphs.",
    "Write a Python function that returns the n-th Fibonacci number iteratively, with a docstring.",
    "What is 17 * 23? Show the multiplication step by step.",
    "Summarize the plot of Romeo and Juliet in five sentences.",
    "Translate to French: 'The train leaves at seven, so we should have breakfast early.'",
    "List three differences between TCP and UDP.",
    "Write a haiku about a lighthouse in winter.",
    "A farmer has 17 sheep and all but 9 die. How many are left? Explain briefly.",
    "Give me a SQL query that finds the five customers with the highest total order value.",
    "What are the main causes of the French Revolution? Answer in a bulleted list.",
    "Explain the difference between a process and a thread to a beginner.",
    "Write a bash one-liner that counts the lines in every .py file under the current directory.",
    "If a train travels 60 miles in 45 minutes, what is its speed in miles per hour?",
    "Describe how a hash map works and what happens on a collision.",
    "Write a limerick about a cat who learned to code.",
    "What is the capital of Australia, and why is it not Sydney?",
    "Convert 72 degrees Fahrenheit to Celsius and show the formula.",
    "Explain what a CUDA warp is and why warp divergence hurts performance.",
    "Write a short product description for a reusable water bottle.",
    "What is the time complexity of binary search, and why?",
    "日本の四季について、短い段落で説明してください。",
    "Escribe tres consejos para dormir mejor.",
    "Write a regular expression that matches a valid IPv4 address and explain each part.",
    "Why does ice float on water?",
    "Give a two-sentence definition of entropy in information theory.",
    "Write a Rust function that reverses a string of Unicode characters.",
    "What should I consider when choosing between renting and buying a home?",
    "Explain gradient descent using an analogy.",
    "Write the opening paragraph of a mystery novel set on a space station.",
    "How do vaccines train the immune system? Keep it under 100 words.",
]
